services:
  mysql:
    image: mysql:8.4
    container_name: subs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: subs-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8081:80"

  redis:
      image: redis:latest
      container_name: subs-redis
      restart: always
      ports:
        - "6379:6379"
      command: [ "redis-server", "--save", "", "--appendonly", "no" ]

volumes:
  mysql_data:
